version: 0.2

env:
  variables:
    AWS_REGION: ca-central-1
    CLUSTER_NAME: charming-jazz-otter
    ECR_REPOSITORY_URI: 148761682921.dkr.ecr.ca-central-1.amazonaws.com/ruthinecr

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 148761682921.dkr.ecr.ca-central-1.amazonaws.com
      - echo Updating kubeconfig...
      - aws eks --region ca-central-1 update-kubeconfig --name charming-jazz-otter

  build:
    commands:
      - echo Building Docker image...
      - docker build -t ruthinecr .
      - docker tag ruthinecr:latest 148761682921.dkr.ecr.ca-central-1.amazonaws.com/ruthinecr:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 148761682921.dkr.ecr.ca-central-1.amazonaws.com/ruthinecr:latest
      - echo Updating Kubernetes deployment...
      -  sed -i "s|linux_148761682921.dkr.ecr.ca-central-1.amazonaws.com/ruthinecr:latest|g" deploy.yml
      - kubectl apply -f deployment.yml --validate=false
      - echo "Deployment successful!"

artifacts:
  files:
    - imagedefinitions.json
