version: 0.2

env:
  variables:
    AWS_REGION: ca-central-1
    CLUSTER_NAME: charming-jazz-otter
    ECR_REPOSITORY_URI: "124355670627.dkr.ecr.us-east-1.amazonaws.com/mounikarepopvt"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - echo Updating kubeconfig...
      - aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME

  build:
    commands:
      - echo Building Docker image...
      - docker build -t mounikarepopvt .
      - docker tag mounikarepopvt:latest $ECR_REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPOSITORY_URI:latest
      - echo Updating Kubernetes deployment...
      - sed -i "s|image:.*|image: $ECR_REPOSITORY_URI:latest|" deployment.yml
      - kubectl apply -f deployment.yml --validate=false
      - echo "Deployment successful!"

artifacts:
  files:
    - imagedefinitions.json
