apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ruthin-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-ruthin-app
  template:
    metadata:
      labels:
        app: my-ruthin-app
    spec:
      containers:
        - name: my-ruthin-app
          image: 148761682921.dkr.ecr.ca-central-1.amazonaws.com/3/18/ruthin:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: my-ruthin-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
